### ISSUE TITLE
Mentions should include @username

### ISSUE THREAD

**Issue by aerth** [dm8tbr/irssi-xmpp-notify#12]
Hey @dm8tbr , when someone notifies a user with the "at sign", it doesn't notify... (i am sure here on github it does). Can anyone reproduce this?

btw thanks for an awesome thing

**Comment by dm8tbr** [comment]
If I understand you correctly you mean that if someone on IRC says "So, @aerth bla bla bla" you don't get a notification?
Does *irssi* show a hilight in that case? IOW: If you are in a different window, does the particular window number turn red?
If not, then it's something you need to fine tune in your irssi config. By default it only hilights the current nickname under certain conditions. I don't remember the details, as my config is now 10+ years old, but you might need to explicitly add your nickname to the hilight list. */help hilight* should give you details for the version you are running.

**Comment by dm8tbr** [comment]
Is this still an issue? Does it concern my script?

**Comment by aerth** [comment]
Thanks for getting back to me. Checking now!

**Comment by aerth** [comment]
Alright thanks for getting back to me. Like you said, definitely works with @username, only after using ```"/hilight @username"```

Same with ```"/hilight username:"```
